"""init tables

Revision ID: 85d0c6059ad6
Revises: 
Create Date: 2024-05-05 23:23:19.067259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d0c6059ad6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('buy', sa.String(), nullable=False),
    sa.Column('sell', sa.String(), nullable=False),
    sa.Column('change_rate', sa.String(), nullable=False),
    sa.Column('change_price', sa.String(), nullable=False),
    sa.Column('high', sa.String(), nullable=False),
    sa.Column('low', sa.String(), nullable=False),
    sa.Column('vol', sa.String(), nullable=False),
    sa.Column('vol_value', sa.String(), nullable=False),
    sa.Column('last', sa.String(), nullable=False),
    sa.Column('average_price', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_name'], ['symbols.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_id'), 'statistics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_id'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    # ### end Alembic commands ###
