version: '3.6'

services:
  producer:
    build:
      context: ../../src/crypto
      dockerfile: producer.Dockerfile
    env_file: ../../.env
    environment:
      CONTAINER_MODE: 1
    command: ["python", "producer/produce.py"]